### ISSUE TITLE
您好，請問能否提供 Vehicle-Color-24 Dataset的 VOC label 資料 (bbox location + class)

### ISSUE THREAD

**Issue by CodingMonkey3688** [mendy-2013/Vehicle-Color-24-Dataset#2]
您好，感謝您分享這麼棒的資料集
請問能否提供 Vehicle-Color-24 Dataset的 VOC label 資料 (bbox location + class) ? 謝謝。

**Comment by mendy-2013** [comment]
您好，您可以
通过百度网盘分享的文件：VOC2012.…
链接:https://pan.baidu.com/s/1ovUFDQjRCzjadi9Kx4PRZQ?pwd=9n26 
提取码:9n26
复制这段内容打开「百度网盘APP 即可获取」
在这个压缩包中有一个名为Annotations的文件夹，里面即为您需要的label数据集。

发件人：CodingMonkey3688 ***@***.***>
发送日期：2022-11-28 16:50:51
收件人：mendy-2013/Vehicle-Color-24-Dataset ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[mendy-2013/Vehicle-Color-24-Dataset] 您好，請問能否提供 Vehicle-Color-24 Dataset的 VOC label 資料 (bbox location + class) (Issue #2)

您好，感謝您分享這麼棒的資料集
 請問能否提供 Vehicle-Color-24 Dataset的 VOC label 資料 (bbox location + class) ? 謝謝。

**Comment by CodingMonkey3688** [comment]
謝謝。
